### ISSUE TITLE
Problem with merge specific file

### ISSUE THREAD

**Issue by ttv20** [raulbojalil/docx-builder#5]
[013.docx](https://github.com/raulbojalil/docx-builder/files/2553390/013.docx)
When I try to merge this file this error appears:
```
TypeError: Cannot read property '_data' of null
    at exports.Document.getExternalDocxRawXml (/*****/node/node_modules/docx-builder/index.js:293:28)
    at exports.Document.insertDocxSync (/*****/node/node_modules/docx-builder/index.js:314:18)
```

**Comment by zubairat** [comment]
same here trying to merge two document created with dock docxtemplater
